name: Create New RSPEC

# Workflow runs when manually triggered using the UI or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      languages:
        description: 'Comma-separated list of targeted languages'
        required: true

jobs:
  create_new_rule:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: true
        ref: master
        path: 'rspec'

    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: 'Install Pipenv'
      run: |
        pip install pipenv

    - name: 'Install rspec-tools'
      working-directory: 'rspec/rspec-tools'
      run: pipenv install -e .

    - name: 'Create Rule'
      working-directory: 'rspec/rspec-tools'
      run: pipenv run rspec-tools create-rule --languages "${{ github.event.inputs.languages }}"
